-- V1: Initial banking schema.

CREATE TABLE customers (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    email         VARCHAR(255) UNIQUE,
    password      VARCHAR(255) NOT NULL,
    branch        VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL DEFAULT 'USER'
);

CREATE TABLE accounts (
    account_number VARCHAR(255) PRIMARY KEY,
    account_type   VARCHAR(255)     NOT NULL,
    balance        DOUBLE PRECISION NOT NULL,
    customer_id    BIGINT,
    CONSTRAINT fk_accounts_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE transactions (
    transaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount           DOUBLE PRECISION NOT NULL,
    transaction_type VARCHAR(255)     NOT NULL,
    transaction_date DATE,
    account_number   VARCHAR(255),
    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_number) REFERENCES accounts (account_number)
);

CREATE INDEX idx_accounts_customer_id ON accounts (customer_id);
CREATE INDEX idx_transactions_account_number ON transactions (account_number);
